Objective

-The objective of this lab is to learn how to capture live network traffic using Wireshark, 
identifying the correct network interface, and become familiar with Wireshark's interface.

Command Used

-ping google.com

Actions Performed

-Opened Wireshark.

-Selected the active network interface.

-Started packet capture.

-Generated network traffic using the ping command.

-Stopped the packet capture.

-Reviewed the captured packets.

Findings

-Wireshark successfully captured live network traffic from the selected interface. 
During the capture, ICMP packets generated by the ping command were visible alongside other
background traffic produced by the operating system.

Analysis

-Wireshark monitors all traffic that passes through the selected network interface.
Even before generating traffic manually, packets were visible because the operating system continuously communicates with network services.
Wireshark captures live network traffic in real time.

Lesson Learned

-A capture must be started on the correct network interface.

-Computers generate background network traffic even when the user is not actively browsing.

-The ping command generates ICMP packets that are visible in Wireshark.

-Each captured packet contains information that can be analyzed to understand network communication.

Screenshots 

- Selecting a network interface

 ![ Network Interface](images/network-Interface.png)

- ICMP Traffic captured

![ ICMP Traffic](images/icmp-traffic.png)



